apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: testevents02
  namespace: default
spec:
  serviceAccountName: events-sa
  mode: Resource
  resources:
  - apiVersion: v1
    kind: Event
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: testchannel