apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: sub2
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: testchannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: channel-display1
